name: Node Continuous Integrations

on: push

jobs:
    test_push_request:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 8
            - run: echo "before run npm ci"
            - run: npm ci
            - run: npm test
            - run: npm run build