name: Node Continuous Integrations

on: push

jobs:
    test_push_request:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 8
            - run: echo "before run npm ci"
            - run: npm ci
            - run: npm test
        steps:
            - name: Composer dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: Prepare Laravel Application
              run : |
                cp .env.example .env
                php artisan key:generate
            - name: Run Testing Project
              run: vendor/phpunit tests/