name: Github Continuous Integrations

on: push

jobs:
    workflows:
        runs-on: ubuntu-18.04
        steps:
            - name: Cache folder
              uses: actions/cache@v1
            - run: echo "Folder caching..."              
              with:
                path: | 
                  vendor/
                  node_modules/

            - name: Hello world
              run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
              env:
                FIRST_NAME: HoangX
                middle_name: Raiser
                Last_Name: Hydraw
              uses: actions/checkout@v2
              uses: actions/setup-node@v1
              with:
                node-version: 8
            - run: echo "run and test npm"
            - run: |
                   npm install
                   npm ci
                   npm test

            - name: Composer dependencies
              run: | 
                composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
                composer update
            - name: Prepare Laravel Application
              run : |
                cp .env.example .env
                php artisan key:generate
                php artisan config:clear

            - name: Run Testing Project
              run: vendor/bin/phpunit tests/