name: Github Continuous Integrations

on: push

jobs:
    workflows:
        runs-on: ubuntu-18.04
        steps:
            - name: Hello world
              run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
              env:
                FIRST_NAME: HoangX
                middle_name: Raiser
                Last_Name: Hydraw
              uses: |
                    actions/checkout@v2
                    actions/setup-node@v1
              with:
                node-version: 8